const courses = [
  {
    id: "C001",
    title: "Advanced Mathematics - Calculus & Algebra",
    description: "Master calculus, algebra, and analytical geometry with comprehensive problem-solving techniques",
    category: "Mathematics",
    level: "Advanced",
    duration: "12 weeks",
    price: 299,
    originalPrice: 399,
    rating: 4.8,
    totalStudents: 1247,
    lessonsCount: 48,
    certificateProvided: true,
    thumbnail: "https://images.unsplash.com/photo-1509228627152-72ae9ae6848d?w=400&h=250&fit=crop",
    topics: ["Differential Calculus", "Integral Calculus", "Linear Algebra", "Analytical Geometry", "Mathematical Proofs"],
    teacherId: "T001",
    features: ["Live Sessions", "Doubt Clearing", "Practice Tests", "Certificate"],
    startDate: "2025-08-01",
    language: "English/Hindi",
    prerequisites: ["Basic Algebra", "Trigonometry"],
    tags: ["Popular", "Trending"]
  },
  {
    id: "C002",
    title: "Quantum Physics & Thermodynamics",
    description: "Explore quantum mechanics, thermodynamics, and modern physics concepts with practical applications",
    category: "Physics",
    level: "Expert",
    duration: "16 weeks",
    price: 449,
    originalPrice: 599,
    rating: 4.9,
    totalStudents: 892,
    lessonsCount: 64,
    certificateProvided: true,
    thumbnail: "https://images.unsplash.com/photo-1635070041078-e363dbe005cb?w=400&h=250&fit=crop",
    topics: ["Quantum Mechanics", "Thermodynamics", "Statistical Physics", "Atomic Physics", "Nuclear Physics"],
    teacherId: "T002",
    features: ["Lab Sessions", "Virtual Experiments", "Research Projects", "Certification"],
    startDate: "2025-08-15",
    language: "English",
    prerequisites: ["Classical Physics", "Calculus"],
    tags: ["Expert Level", "Research Oriented"]
  },
  {
    id: "C003",
    title: "English Literature & Grammar Mastery",
    description: "Comprehensive course covering literature analysis, creative writing, and advanced grammar concepts",
    category: "English",
    level: "Intermediate",
    duration: "10 weeks",
    price: 199,
    originalPrice: 299,
    rating: 4.7,
    totalStudents: 1856,
    lessonsCount: 40,
    certificateProvided: true,
    thumbnail: "https://images.unsplash.com/photo-1481627834876-b7833e8f5570?w=400&h=250&fit=crop",
    topics: ["Literature Analysis", "Creative Writing", "Grammar Rules", "Poetry Analysis", "Essay Writing"],
    teacherId: "T003",
    features: ["Writing Workshops", "Peer Reviews", "Publication Guide", "Certificate"],
    startDate: "2025-07-20",
    language: "English",
    prerequisites: ["Basic English"],
    tags: ["Bestseller", "Creative"]
  },
  {
    id: "C004",
    title: "Organic Chemistry Fundamentals",
    description: "Master organic chemistry with reaction mechanisms, synthesis strategies, and laboratory techniques",
    category: "Chemistry",
    level: "Intermediate",
    duration: "14 weeks",
    price: 349,
    originalPrice: 449,
    rating: 4.6,
    totalStudents: 743,
    lessonsCount: 56,
    certificateProvided: true,
    thumbnail: "https://images.unsplash.com/photo-1532187643603-ba119ca4109e?w=400&h=250&fit=crop",
    topics: ["Reaction Mechanisms", "Organic Synthesis", "Stereochemistry", "Spectroscopy", "Medicinal Chemistry"],
    teacherId: "T004",
    features: ["Virtual Lab", "Reaction Database", "Practice Problems", "Certificate"],
    startDate: "2025-08-10",
    language: "English/Hindi",
    prerequisites: ["General Chemistry"],
    tags: ["Hands-on", "Lab Intensive"]
  },
  {
    id: "C005",
    title: "Genetics & Molecular Biology",
    description: "Comprehensive study of genetics, molecular biology, and biotechnology applications",
    category: "Biology",
    level: "Advanced",
    duration: "18 weeks",
    price: 399,
    originalPrice: 549,
    rating: 4.8,
    totalStudents: 567,
    lessonsCount: 72,
    certificateProvided: true,
    thumbnail: "https://images.unsplash.com/photo-1559757148-5c350d0d3c56?w=400&h=250&fit=crop",
    topics: ["Molecular Genetics", "Gene Expression", "DNA Technology", "Biotechnology", "Genetic Engineering"],
    teacherId: "T005",
    features: ["Case Studies", "Research Papers", "Lab Simulations", "Certificate"],
    startDate: "2025-09-01",
    language: "English",
    prerequisites: ["Cell Biology", "Biochemistry"],
    tags: ["Research Focus", "NEET Prep"]
  },
  {
    id: "C006",
    title: "Data Structures & Algorithms Mastery",
    description: "Complete guide to data structures, algorithms, and competitive programming techniques",
    category: "Computer Science",
    level: "Advanced",
    duration: "20 weeks",
    price: 499,
    originalPrice: 699,
    rating: 4.9,
    totalStudents: 2341,
    lessonsCount: 80,
    certificateProvided: true,
    thumbnail: "https://images.unsplash.com/photo-1555949963-aa79dcee981c?w=400&h=250&fit=crop",
    topics: ["Data Structures", "Algorithm Design", "Dynamic Programming", "Graph Theory", "Competitive Programming"],
    teacherId: "T006",
    features: ["Coding Challenges", "Interview Prep", "Live Coding", "Certificate"],
    startDate: "2025-07-25",
    language: "English",
    prerequisites: ["Basic Programming", "Mathematics"],
    tags: ["Job Ready", "Interview Prep"]
  }
];
